### ISSUE TITLE
No support for Astro/Astro's client directives?

### ISSUE THREAD

**Issue by joeyfigaro** [thecuvii/remark-sandpack#2]
Hey @thecuvii! Thank you for your work on this–it's very easy to use. The issue I'm running into involves Astro. I've got Sandpack rendering as expected from MDX content, but the component is never hydrated so it's not interactive at all. Passing astro's client directives causes the entire site to fail to render. 

Have you had any experience getting this to work in Astro?

**Comment by thecuvii** [comment]
Sorry, I haven't tested it with Astro yet. 
Could you provide a minimal reproduction repository? I'll try to fix it asap.

**Comment by thecuvii** [comment]
Hi joey, I've add a new astro example. please checkout: https://github.com/thecuvii/remark-sandpack/blob/master/examples/astro/src/pages/index.mdx


https://github.com/thecuvii/remark-sandpack/assets/11806619/51a98900-44c0-4806-804f-8711b6995cf0

Everything just works with `client:load` directive.
